# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/kinzie/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files

$(call inherit-product, vendor/motorola/kinzie/kinzie-vendor-blobs.mk)

# Prebuilt APKs
PRODUCT_PACKAGES += \
    atfwd \
    MotGeoFenceSvc \
    MotoSignatureApp \
    TimeService

# Prebuilt jars
PRODUCT_PACKAGES += \
    cneapiclient \
    com.motorola.motosignature \
    com.quicinc.cne \
    org.simalliance.openmobileapi \
    qcnvitems \
    qcrilhook

# Prebuilt privileged APKs
PRODUCT_PACKAGES += \
    CNEService \
    com.qualcomm.location \
    qcrilmsgtunnel

# Prebuilt multilibs
PRODUCT_PACKAGES += \
    libtime_genoff.so

